### ISSUE TITLE
What is the purpose of this fork?

### ISSUE THREAD

**Issue by zx8** [krader1961/fish#15]
Hi Kurtis

Being a long-time fish user who closely follows the upstream PRs and issues, I've noticed that recently you've [been](https://github.com/fish-shell/fish-shell/issues/4353#issuecomment-324805629) [commenting](https://github.com/fish-shell/fish-shell/issues/4355#issuecomment-325092560) on upstream issues with references to fixes in your personal fork, rather than simply raising an upstream PR, as well as creating duplicate issues both here and upstream.

I'm slightly confused as to why you're opting to contribute changes in this way. As a loyal fish fanatic, should I be concerned? 😄 

Thanks

**Comment by krader1961** [comment]
> should I be concerned?

Hard to say. I hope not but I'll be surprised if six months from now the official fish project hasn't reverted to the state I found it in October 2015. That is, infrequent releases, PRs left moldering, little innovation.

I left the project because within minutes of my implementing a builtin `math` command another developer said it should be reverted because supporting anything other than the four basic arithmetic operators wasn't needed and we should just write our own `math` implementation that just does integer arithmetic with support for `+`, `-`, `*`, and `/`. I kinda snapped; especially since that person was raising concerns they should have voiced in the year that https://github.com/fish-shell/fish-shell/issues/3157 was open. Not to mention before I had spent 30+ hours to implement it. I decided it was bad for my mental health to continue arguing with that person (this wasn't the first issue we had clashed over).

P.S., That person also thinks we should have implemented a simple lisp like polish notation. Which means that rather than write `set x (math '(1 + (3 * 5)) / 10) - 9)` you would write `set x (sub (div (add 1 (mul 3 5)) 10) 9)`.

**Comment by zx8** [comment]
Having read through both https://github.com/fish-shell/fish-shell/issues/3157 and Gitter chats, I now better understand the situation.

As a user who was having fun playing with the new `math` builtin – including things like the shiny new `min` / `max` functions – and (without intending to offend) noting that the developer in question hasn't contributed much of significance back to the fish project in close to a year, I find it hard to accept that you're leaving the project solely due to an opinion raised by said individual.

Please remember there are people beyond the developers of the project, like us, the _users_, who hugely value the time and effort you put into the project. It would be a **huge** shame to see you go and hope you can work out your differences, for the sake of the users.

If not... so long, and thanks for all the `fish`.

**Comment by krader1961** [comment]
Thanks for the feedback, @zx8. What you're not aware of are all the other clashes I've had with that developer. The argument over the builtin `math` command was just the straw that broke this camel's back. Faho and Zanchey have attempted to direct that person in more fruitful directions but with limited success. The lead for this project seems to like the individual I'm clashing with more than me. Can't say that I blame him since I'm not the easiest person to work with given my strong opinions about what is best for the project. Especially with respect to items like implementing a consistent code style and paying attention to lint errors that don't seem like very important issues to most people. Issues I made a priority to address in my first few months contributing to the project.

I may return to contributing in a more typical manner in a few weeks or months when I have cooled down. Until then I'll make improvements to my fork and announce them to the main project. The fish-shell team can either incorporate my improvements or not as they see fit. If they do incorporate my changes, especially if the person I have a problem with does the work, it will make me more likely to abandon my fork. If not then I'll continue to maintain my fork. Eventually the marketplace will decide.

**Comment by alphapapa** [comment]
Kurtis,

I'm sorry to hear that you've stepped away from fish.  While I have gently butted heads with you in a few discussions, we always came to an understanding, if not necessarily full agreement.  I respect your technical opinions and appreciate your work on fish.

As for `math`, it wasn't an easy call.  While the increase in the binary size was a mild concern, I think you made a reasonable decision; and since you're the one doing the work, and since you *are* competent to do so, I think you earned the right to make it.  Talk is cheap; code walks (or something like that).

So, do take a break; you've earned it.  You don't get paid for this, so you shouldn't do it if it stops being enjoyable (or if the stress outweighs the joy).  I hope that with time and perspective, you will return to the project so we may continue to enjoy the fruits of your labors.

Cheers!

**Comment by krader1961** [comment]
Thanks, @alphapapa, for the feedback. I know I can be acerbic when responding to proposals I don't think have been well thought out or which I think are downright silly. :smile: Our first couple of interactions were more confrontational than they should have been because I tend to be quick to criticize what I think are silly proposals. I eventually realized that you and I were mostly on the same page. I was simply not making adequate allowance for the Internet making it too easy for people to make a comment or proposal without careful consideration. Something I'm also guilty of as evidenced by the current situation after I told that other developer to "F**k off" when they threatened to revert my commit while simultaneously stating that they were not interested in doing any work to implement an alternative solution to the issue.

I certainly don't want to maintain my own fork. But neither can I work with the developer I clashed with if the rest of the team isn't going to aggressively rein in that person's more absurd proposals. Such as implementing polish notation as an alternative to our `math` command that uses infix notation. Or reverting a change because it increased the size of the binary to 2 MB. A size increase I agree is undesirable. Had that person simply said something like "We need to explore ways to solve the problem with a smaller size increase", and opened an issue to that effect, I would have wholeheartedly agreed.
